### ISSUE TITLE
Crash on loading, Fabric 1.18.2, when no trinkets is present

### ISSUE THREAD

**Issue by rrusciguy** [Mari023/AE2WirelessTerminalLibrary#131]
I've narrowed the crash down to this mod. No crash with everything but this mod enabled, crashes even with just this mod and AE2 enabled. 

MC 1.18.2
Fabric 0.13.3
AE2 11.0.0 alpha1
AE2Wireless 10.1.1 beta 6

I would attach a crash log, however one did not seem to be generated, even after repeating the crash multiple times, unless the CF app is putting them somewhere other than the usual folder.

from console output:

```
00:15:24.030
net.minecraft.client.main.Main
Render thread
Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=air}]
	at net.minecraft.class_2370.method_40276(class_2370.java:330)
	at net.minecraft.class_2378.method_40292(class_2378.java:369)
	at net.minecraft.class_310.handler$bbi001$onStart(class_310.java:8985)
	at net.minecraft.class_310.method_1514(class_310.java:716)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
00:15:24.040
net.minecraft.class_310
Render thread
Stopping!
00:15:24.090
net.minecraft.class_310
Render thread
Shutdown failure!
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.forEach(HashMap.java:1424)
	at net.minecraft.class_1060.close(class_1060.java:173)
	at net.minecraft.class_310.close(class_310.java:1048)
	at net.minecraft.class_310.method_1490(class_310.java:1026)
	at net.minecraft.client.main.Main.main(Main.java:252)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
00:15:24.782
launcher
main

00:15:24.782
monitor
Process Monitor
Process ended with exit code 0

```

**Comment by Mari023** [comment]
I think I messed up something with my Trinkets compat.
It should stop crashing if you add Trinkets

My guess this is because I always add the trinket tags, and it seems 1.18.2 doesn't like adding tags which don't exist.

**Comment by Mari023** [comment]
I found the root cause, I used to register an item when trinkets was installed and enabled, to disallow joining a server that has trinkets enabled with a client that has it disabled.
apparently 1.18.2 doesn't like instanced but not registered items.

The next version of ae2wtlib will fix this issue, for now, you just have to install trinkets.
