### ISSUE TITLE
[Fabric] Failed to start server with AE2WTLib 11.1.0

### ISSUE THREAD

**Issue by Daturachan** [Mari023/AE2WirelessTerminalLibrary#140]
**Minecraft version:** 1.18.2
**Fabric loader version:** 0.14.6
**Fabric API version:** 0.55.1+1.18.2
**AE2 version:** 11.1.0

Server fails to start when the latest version of AE2WTLib is installed. As soon as it's removed, server starts without a hitch.

Not Enough Crashes wrongly reports the issue being caused by AE2 itself, but here are the relevant log lines anyway.
Can't provide a crash log as the server doesn't actually crash, it "just" doesn't start.

```
10:54:17] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'ae2'!
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.6.jar:?]
	at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.6.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [fabric-0.14.6-mc.1.18.2.jar:0.10.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_304
	at appeng.client.Hotkeys.createHotkey(Hotkeys.java:15) ~[appliedenergistics2-11.1.0.jar:?]
	at appeng.client.Hotkeys.registerHotkey(Hotkeys.java:24) ~[appliedenergistics2-11.1.0.jar:?]
	at appeng.hotkeys.HotkeyActions.register(HotkeyActions.java:67) ~[appliedenergistics2-11.1.0.jar:?]
	at appeng.hotkeys.HotkeyActions.<clinit>(HotkeyActions.java:25) ~[appliedenergistics2-11.1.0.jar:?]
	at de.mari_023.ae2wtlib.wut.WUTHandler.addTerminal(WUTHandler.java:157) ~[AE2WTLib-11.1.0.jar:?]
	at de.mari_023.ae2wtlib.AE2wtlib.onAe2Initialized(AE2wtlib.java:44) ~[AE2WTLib-11.1.0.jar:?]
	at de.mari_023.ae2wtlib.fabric.AE2wtlibEntrypoint.onAe2Initialized(AE2wtlibEntrypoint.java:20) ~[AE2WTLib-11.1.0.jar:?]
	at appeng.core.AppEngBase.notifyAddons(AppEngBase.java:311) ~[appliedenergistics2-11.1.0.jar:?]
	at appeng.core.AppEngServer.<init>(AppEngServer.java:31) ~[appliedenergistics2-11.1.0.jar:?]
	at appeng.core.AppEngServerStartup.onInitializeServer(AppEngServerStartup.java:9) ~[appliedenergistics2-11.1.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_304
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at appeng.client.Hotkeys.createHotkey(Hotkeys.java:15) ~[appliedenergistics2-11.1.0.jar:?]
	at appeng.client.Hotkeys.registerHotkey(Hotkeys.java:24) ~[appliedenergistics2-11.1.0.jar:?]
	at appeng.hotkeys.HotkeyActions.register(HotkeyActions.java:67) ~[appliedenergistics2-11.1.0.jar:?]
	at appeng.hotkeys.HotkeyActions.<clinit>(HotkeyActions.java:25) ~[appliedenergistics2-11.1.0.jar:?]
	at de.mari_023.ae2wtlib.wut.WUTHandler.addTerminal(WUTHandler.java:157) ~[AE2WTLib-11.1.0.jar:?]
	at de.mari_023.ae2wtlib.AE2wtlib.onAe2Initialized(AE2wtlib.java:44) ~[AE2WTLib-11.1.0.jar:?]
	at de.mari_023.ae2wtlib.fabric.AE2wtlibEntrypoint.onAe2Initialized(AE2wtlibEntrypoint.java:20) ~[AE2WTLib-11.1.0.jar:?]
	at appeng.core.AppEngBase.notifyAddons(AppEngBase.java:311) ~[appliedenergistics2-11.1.0.jar:?]
	at appeng.core.AppEngServer.<init>(AppEngServer.java:31) ~[appliedenergistics2-11.1.0.jar:?]
	at appeng.core.AppEngServerStartup.onInitializeServer(AppEngServerStartup.java:9) ~[appliedenergistics2-11.1.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.6.jar:?]
	... 8 more
```

**Comment by Mari023** [comment]
while this is for fabric, and #139 is for forge, this is the same underlying issue

**Comment by Mari023** [comment]
>Not Enough Crashes wrongly reports the issue being caused by AE2 itself 

funnily enough, this is actually an ae2 issue (still my fault tho)
