### ISSUE TITLE
Restock locks up ae2 (AE2WTLib-12.8.6)

### ISSUE THREAD

**Issue by nhammond129** [Mari023/AE2WirelessTerminalLibrary#198]
Enabling restock from ae2 breaks adding/removing items entirely until server restart.

Full log: [latest.log](https://github.com/Mari023/AE2WirelessTerminalLibrary/files/11283410/latest.log) (`^f` for "MARKER1" on line `2753` to jump to the exception)

Immediately-relevant snippet:
```
[20Apr2023 02:04:41.797] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: <Nullspeaker> enabling restock:
[20Apr2023 02:04:43.852] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 51
	Listeners:
		0: HIGH
		1: ASM: class tschipp.carryon.events.CommonEvents onBlockClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		2: ASM: class dev.architectury.event.forge.EventHandlerImplCommon eventPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		3: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onUseBlockHP(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		4: NORMAL
		5: ASM: mob_grinding_utils.events.FillXPBottleEvent@1f818762 clickBottle(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		6: ASM: class lilypuree.decorative_blocks.events.CallBacks onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		7: ASM: class chiefarug.mods.systeams.block.BoilerBlock use(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		8: net.minecraftforge.eventbus.EventBus$$Lambda$4639/0x0000000800ca72d8@72fb3822
		9: net.minecraftforge.eventbus.EventBus$$Lambda$4639/0x0000000800ca72d8@5a126f13
		10: ASM: class com.hollingsworth.arsnouveau.common.camera.CameraEvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		11: ASM: class com.hollingsworth.arsnouveau.client.events.PlayerEvent onBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		12: ASM: com.catastrophe573.dimdungeons.PlayerDungeonEvents@19708b61 rightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		13: net.minecraftforge.eventbus.EventBus$$Lambda$4639/0x0000000800ca72d8@471815fd
		14: ASM: vazkii.quark.content.building.module.StoolsModule@1694bd75 itemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		15: ASM: vazkii.quark.content.building.module.ShearVinesModule@6b3a57e1 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		16: ASM: vazkii.quark.content.tweaks.module.SimpleHarvestModule@5fe5855a onClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		17: ASM: vazkii.quark.content.tweaks.module.SignEditingModule@1b393059 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		18: ASM: vazkii.quark.content.tweaks.module.ShulkerPackingModule@7f19b134 callFedEnd(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		19: ASM: vazkii.quark.content.tweaks.module.ReplaceScaffoldingModule@7a2c58b6 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		20: ASM: vazkii.quark.content.tweaks.module.EnhancedLaddersModule@50a33fbd onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		21: ASM: vazkii.quark.content.tweaks.module.DyeableItemFramesModule@2818529f onUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		22: ASM: class com.blamejared.crafttweaker.impl.event.CTCommonEventHandler blockInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		23: ASM: class vazkii.quark.base.handler.ToolInteractionHandler itemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		24: ASM: class com.mrh0.createaddition.event.GameEvents interact(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		25: net.minecraftforge.eventbus.EventBus$$Lambda$4639/0x0000000800ca72d8@5b729681
		26: ASM: class com.simibubi.create.foundation.tileEntity.behaviour.linked.LinkHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		27: ASM: class com.simibubi.create.foundation.tileEntity.behaviour.filtering.FilteringHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		28: ASM: class com.simibubi.create.foundation.tileEntity.behaviour.edgeInteraction.EdgeInteractionHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		29: ASM: class com.simibubi.create.foundation.block.ItemUseOverrides onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		30: ASM: class com.simibubi.create.content.logistics.block.funnel.FunnelItem funnelItemAlwaysPlacesWhenUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		31: ASM: class com.simibubi.create.content.logistics.block.display.DisplayLinkBlockItem gathererItemAlwaysPlacesWhenUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		32: ASM: class com.simibubi.create.content.contraptions.components.structureMovement.glue.SuperGlueItem glueItemAlwaysPlacesWhenUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		33: ASM: class com.simibubi.create.content.contraptions.components.deployer.ManualApplicationRecipe manualApplicationRecipesApplyInWorld(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		34: ASM: Block{minecraft:air} rightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		35: net.minecraftforge.eventbus.EventBus$$Lambda$4639/0x0000000800ca72d8@70639fe5
		36: net.minecraftforge.eventbus.EventBus$$Lambda$4639/0x0000000800ca72d8@39c01c0d
		37: net.minecraftforge.eventbus.EventBus$$Lambda$4639/0x0000000800ca72d8@3ef05135
		38: ASM: shadows.apotheosis.ench.EnchModuleEvents@5f585517 rightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		39: net.minecraftforge.eventbus.EventBus$$Lambda$4639/0x0000000800ca72d8@71791ef4
		40: ASM: mekanism.common.CommonPlayerTracker@3844f7b3 rightClickEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		41: ASM: de.maxhenkel.pipez.events.BlockEvents@4cfa7c42 onBlockClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		42: ASM: blusunrize.immersiveengineering.common.EventHandler@f15e522 onBlockRightclick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		43: ASM: mob_grinding_utils.events.ChickenFuseEvent@255cd2f1 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		44: LOW
		45: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onUseBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		46: LOWEST
		47: net.minecraftforge.eventbus.EventBus$$Lambda$4639/0x0000000800ca72d8@1d092b89
		48: ASM: class ovh.corail.tombstone.event.EventHandler onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		49: ASM: class cofh.lib.util.ItemTracker onUseOn(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		50: net.minecraftforge.eventbus.EventBus$$Lambda$4639/0x0000000800ca72d8@24107c51
		51: ASM: class de.mari_023.ae2wtlib.AE2wtlibForge handle(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		52: net.minecraftforge.eventbus.EventBus$$Lambda$4639/0x0000000800ca72d8@1855f81f
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at TRANSFORMER/ae2@12.9.3/appeng.api.stacks.KeyCounter.get(KeyCounter.java:106)
	at TRANSFORMER/ae2@12.9.3/appeng.util.prioritylist.PrecisePriorityList.isListed(PrecisePriorityList.java:34)
	at TRANSFORMER/ae2@12.9.3/appeng.util.prioritylist.IPartitionList.matchesFilter(IPartitionList.java:42)
	at TRANSFORMER/ae2@12.9.3/appeng.me.storage.MEInventoryHandler.passesBlackOrWhitelist(MEInventoryHandler.java:145)
	at TRANSFORMER/ae2@12.9.3/appeng.me.storage.MEInventoryHandler.canExtract(MEInventoryHandler.java:140)
	at TRANSFORMER/ae2@12.9.3/appeng.me.storage.MEInventoryHandler.extract(MEInventoryHandler.java:85)
	at TRANSFORMER/ae2@12.9.3/appeng.me.storage.NetworkStorage.extract(NetworkStorage.java:266)
	at TRANSFORMER/ae2wtlib@12.8.6/de.mari_023.ae2wtlib.AE2wtlibForge.restock(AE2wtlibForge.java:101)
	at TRANSFORMER/ae2wtlib@12.8.6/de.mari_023.ae2wtlib.AE2wtlibForge.handle(AE2wtlibForge.java:80)
	at TRANSFORMER/ae2wtlib@12.8.6/de.mari_023.ae2wtlib.__AE2wtlibForge_handle_RightClickBlock.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.8/net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:875)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:320)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1060)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

I can still interact with other parts of the system, but anything involving adding/removing items (submitting crafting jobs, mundane storage, importers) will not succeed.
```
[20Apr2023 02:05:28.146] [Server thread/WARN] [AE2:S/]: Extracted 1xmysticalagriculture:fluix_essence from adjacent storage and voided it because network refused insert
[20Apr2023 02:05:31.707] [Server thread/INFO] [AE2:S/]: Couldn't submit crafting job for 10xae2:crafting_unit: MISSING_INGREDIENT [Detail: GenericStack[what=mysticalagriculture:certus_quartz_essence, amount=6]]
```

**Comment by Mari023** [comment]
Thanks for the very detailed report!
I will release a fix very soon

**Comment by Mari023** [comment]
should be fixed in the next release
