### ISSUE TITLE
Crash while opening inventory

### ISSUE THREAD

**Issue by TayfunAltuntas** [Mari023/AE2WirelessTerminalLibrary#304]
Hello !

I have encountered several crashes while opening my inventory, it's crashing randomly, it is not necessarily the first time i open my inventory. ( i play on the modpack Ragnamod VII)

Here the logs :

---- Minecraft Crash Report ----
// Why did you do that?

Time: 9/9/24, 11:23 AM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "de.mari_023.ae2wtlib.wct.CraftingTerminalHandler.isRestockable(net.minecraft.world.item.ItemStack)" because "handler" is null
	at net.minecraft.client.renderer.entity.ItemRenderer.handler$clp000$renderGuiItemOverlay(ItemRenderer.java:3032) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:ItemRendererMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorItemRenderer,pl:mixin:APP:mixins.codechickenlib.json:ItemRendererMixin,pl:mixin:APP:ae2.mixins.json:ItemRendererMixin,pl:mixin:APP:dankstorage.mixins.json:ItemRendererAccessor,pl:mixin:APP:ae2wtlib.mixins.json:RestockRender,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.item.MixinItemRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115169_(ItemRenderer.java:324) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:ItemRendererMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorItemRenderer,pl:mixin:APP:mixins.codechickenlib.json:ItemRendererMixin,pl:mixin:APP:ae2.mixins.json:ItemRendererMixin,pl:mixin:APP:dankstorage.mixins.json:ItemRendererAccessor,pl:mixin:APP:ae2wtlib.mixins.json:RestockRender,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.item.MixinItemRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at vazkii.quark.content.client.module.UsageTickerModule$TickerElement.render(UsageTickerModule.java:168) ~[Quark-3.2-358.jar%23290!/:3.2-358] {re:classloading}
	at vazkii.quark.content.client.module.UsageTickerModule.renderHUD(UsageTickerModule.java:84) ~[Quark-3.2-358.jar%23290!/:3.2-358] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2721_UsageTickerModule_renderHUD_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:869) ~[forge-1.18.2-40.2.21-universal.jar%23379!/:?] {re:mixin,re:classloading,pl:mixin:APP:embeddium.mixins.json:features.options.MixinInGameHud,pl:mixin:APP:embeddium.mixins.json:features.gui.MixinDebugHud,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.m_93030_(ForgeIngameGui.java:359) ~[forge-1.18.2-40.2.21-universal.jar%23379!/:?] {re:mixin,re:classloading,pl:mixin:APP:embeddium.mixins.json:features.options.MixinInGameHud,pl:mixin:APP:embeddium.mixins.json:features.gui.MixinDebugHud,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:870) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tombstone.mixins.json:GameRendererMixin,pl:mixin:APP:fastload.mixins.json:client.GameRendererMixin,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin,pl:mixin:APP:beyond_earth.mixin.json:BobViewer,pl:mixin:APP:tempad.mixins.json:GameRendererMixin,pl:mixin:APP:justzoom.mixin.json:MixinGameRenderer,pl:mixin:APP:lychee.mixins.json:GameRendererAccess,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.21.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	AE2WTLib (ae2wtlib), Version: 11.6.3
		Issue tracker URL: https://github.com/Mari023/AE2WirelessTerminalLibrary/issues
		Mixin class: de.mari_023.ae2wtlib.mixin.RestockRender
		Target: net.minecraft.client.renderer.entity.ItemRenderer
		at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.renderer.entity.ItemRenderer.handler$clp000$renderGuiItemOverlay(ItemRenderer.java:3032)

	Quark (quark), Version: 3.2-358
		Issue tracker URL: https://github.com/Vazkii/Quark
		at TRANSFORMER/quark@3.2-358/vazkii.quark.content.client.module.UsageTickerModule$TickerElement.render(UsageTickerModule.java:168)
Stacktrace:
	at net.minecraft.client.renderer.entity.ItemRenderer.handler$clp000$renderGuiItemOverlay(ItemRenderer.java:3032) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:ItemRendererMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorItemRenderer,pl:mixin:APP:mixins.codechickenlib.json:ItemRendererMixin,pl:mixin:APP:ae2.mixins.json:ItemRendererMixin,pl:mixin:APP:dankstorage.mixins.json:ItemRendererAccessor,pl:mixin:APP:ae2wtlib.mixins.json:RestockRender,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.item.MixinItemRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.ItemRenderer.m_115169_(ItemRenderer.java:324) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:ItemRendererMixin,pl:mixin:APP:botania_xplat.mixins.json:client.AccessorItemRenderer,pl:mixin:APP:mixins.codechickenlib.json:ItemRendererMixin,pl:mixin:APP:ae2.mixins.json:ItemRendererMixin,pl:mixin:APP:dankstorage.mixins.json:ItemRendererAccessor,pl:mixin:APP:ae2wtlib.mixins.json:RestockRender,pl:mixin:APP:quark.mixins.json:client.ItemRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.item.MixinItemRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at vazkii.quark.content.client.module.UsageTickerModule$TickerElement.render(UsageTickerModule.java:168) ~[Quark-3.2-358.jar%23290!/:3.2-358] {re:classloading}
	at vazkii.quark.content.client.module.UsageTickerModule.renderHUD(UsageTickerModule.java:84) ~[Quark-3.2-358.jar%23290!/:3.2-358] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2721_UsageTickerModule_renderHUD_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.post(ForgeIngameGui.java:869) ~[forge-1.18.2-40.2.21-universal.jar%23379!/:?] {re:mixin,re:classloading,pl:mixin:APP:embeddium.mixins.json:features.options.MixinInGameHud,pl:mixin:APP:embeddium.mixins.json:features.gui.MixinDebugHud,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.m_93030_(ForgeIngameGui.java:359) ~[forge-1.18.2-40.2.21-universal.jar%23379!/:?] {re:mixin,re:classloading,pl:mixin:APP:embeddium.mixins.json:features.options.MixinInGameHud,pl:mixin:APP:embeddium.mixins.json:features.gui.MixinDebugHud,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Samoukhey'/1245, l='ClientLevel', x=-153.92, y=63.00, z=-360.64]]
	Chunk stats: 1024, 612
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,75,-48), Section: (at 0,11,0 in 1,4,-3; chunk contains blocks 16,-64,-48 to 31,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 9733062 game time, 11343143 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.world_ticking.MixinClientLevel,pl:mixin:APP:pluto.mixins.json:fast_entity_access.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:byg.mixins.json:access.client.ClientLevelAccess,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:APP:embeddium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:embeddium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2264) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:687) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23374!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.21.jar%2318!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, Supplementaries Generated Pack, quark-emote-pack, magipsi-2.2.0+1.18.2.jar:magipsi_overrides, resources, Solar Flux Generated Resources, KubeJS Resource Pack [assets]

**Comment by Mari023** [comment]
1.18.2 is not supported anymore.
you should however be able to prevent this crash by deactivating restock
