### ISSUE TITLE
how i fix that ?

### ISSUE THREAD

**Issue by Kirinat0** [Mari023/AE2WirelessTerminalLibrary#75]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ae2wtlib'!

**Comment by Mari023** [comment]
if you can provide me the crashlog (it is in the crashlog folder), I might be able to help you.

**Comment by Kirinat0** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 8/7/21 12:35 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ae2wtlib'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoClassDefFoundError: appeng/container/implementations/MEMonitorableContainer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at de.mari_023.fabric.ae2wtlib.ae2wtlib.onInitialize(ae2wtlib.java:73)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2618/936120380.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.ClassNotFoundException: appeng.container.implementations.MEMonitorableContainer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 305401496 bytes (291 MB) / 1490026496 bytes (1421 MB) up to 4474273792 bytes (4267 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4800m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		ae2wtlib: AE2WTLib 1.1.5-release
		appliedenergistics2: Applied Energistics 2 8.4.0-alpha.1
		fabric: Fabric API 0.37.1+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+6aebe11a7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+95b14da07d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+f941baf07d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+f3e8589e7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+6afaa13c7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+ca0ef93d7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+5f6b94517d
		fabricloader: Fabric Loader 0.11.3
		fasttransferlib: Fast Transfer Lib 0.4.2
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		libblockattributes_core: LibBlockAttributes (Core) 0.8.7
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.7
		libblockattributes_items: LibBlockAttributes (Items) 0.8.7
		libgui: LibGui 3.3.5+1.16.5
		minecraft: Minecraft 1.16.5
		nbtcrafting: NBT Crafting 2.0.19+mc1.16.4
		team_reborn_energy: Energy 0.1.1
		wirelessnetworks: Wireless Networks 1.0.3
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Kirinat0** [comment]
[12:30:21] [main/INFO]: Loading for game Minecraft 1.16.5
[12:30:21] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[12:30:28] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-lookup-api-v1: used 1.2.0+6aebe11a7d, also found 1.2.0+84310a227d
[12:30:28] [main/INFO]: [FabricLoader] Loading 59 mods: fabric-renderer-api-v1@0.4.4+f3e8589e7d, fabric-keybindings-v0@0.2.1+ca58154a7d, ae2wtlib@1.1.5-release, fabricloader@0.11.3, fabric-transfer-api-v1@1.0.0+5f6b94517d, fabric-structure-api-v1@1.1.11+ca0ef93d7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-object-builder-api-v1@1.9.5+c88702897d, fabric-dimensions-v1@2.0.6+61336ba97d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.3.0+c88702897d, appliedenergistics2@8.4.0-alpha.1, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.3.0+2868a2287d, libblockattributes_items@0.8.7, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.37.1+1.16, fabric-particles-v1@0.2.4+ca58154a7d, libblockattributes_core@0.8.7, fabric-networking-v0@0.3.2+ca58154a7d, fabric-api-lookup-api-v1@1.2.0+6aebe11a7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, minecraft@1.16.5, fabric-command-api-v1@1.1.2+95b14da07d, jankson@3.0.1+j1.2.0, fasttransferlib@0.4.2, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.7+8183d3957d, fabric-renderer-indigo@0.4.4+ca58154a7d, wirelessnetworks@1.0.3, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.3+f941baf07d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, libgui@3.3.5+1.16.5, fabric-entity-events-v1@1.1.0+c88702897d, nbtcrafting@2.0.19+mc1.16.4, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.6.0+2868a2287d, fabric-resource-loader-v0@0.4.7+6afaa13c7d, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.10+3661eaa17d, libblockattributes_fluids@0.8.7, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.3+e3c9d0627d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-models-v0@0.3.0+bc7a746f7d, fabric-item-groups-v0@0.2.7+2868a2287d, fabric-object-builders-v0@0.7.2+ca58154a7d, team_reborn_energy@0.1.1
[12:30:28] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/PK/Twitch/Minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[12:30:29] [main/WARN]: Error loading class: appeng/client/gui/implementations/MEMonitorableScreen (java.lang.ClassNotFoundException: appeng/client/gui/implementations/MEMonitorableScreen)
[12:30:29] [main/WARN]: @Mixin target appeng.client.gui.implementations.MEMonitorableScreen was not found ae2wtlib.mixins.json:MeMonitorableScreenWireless
[12:30:29] [main/WARN]: Error loading class: me/ultrablacklinux/minemenufabric/client/screen/MineMenuSelectScreen (java.lang.ClassNotFoundException: me/ultrablacklinux/minemenufabric/client/screen/MineMenuSelectScreen)
[12:30:29] [main/WARN]: @Mixin target me.ultrablacklinux.minemenufabric.client.screen.MineMenuSelectScreen was not found ae2wtlib.mixins.json:MineMenuMixin
[12:30:29] [main/WARN]: Error loading class: me/ultrablacklinux/minemenufabric/client/screen/MineMenuSelectScreen (java.lang.ClassNotFoundException: me/ultrablacklinux/minemenufabric/client/screen/MineMenuSelectScreen)
[12:30:29] [main/WARN]: @Mixin target me.ultrablacklinux.minemenufabric.client.screen.MineMenuSelectScreen was not found ae2wtlib.mixins.json:MineMenuTerminalHandler
[12:30:36] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:30:37] [main/INFO]: Setting user: LuBlade

**Comment by Desempregago** [comment]
Latest AE2 alpha broke AE2WTLib

**Comment by Mari023** [comment]
there is an alpha that works with Applied Energistics 2 8.4.0-alpha.1 and there soon will be an alpha that should work with  Applied Energistics 2 8.4.0-alpha.2
